-- This script was generated by `supabase db diff --use-migra > supabase/migrations/20221216194806_add_tables.sql`

create table "public"."exit_tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "exit_id" uuid not null,
    "tag_id" bigint not null
);


alter table "public"."exit_tags" enable row level security;

create table "public"."exits" (
    "id" uuid not null default uuid_generate_v4(),
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "updated_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "markdown" text not null,
    "tags" character varying[],
    "edit_token" uuid not null default uuid_generate_v4()
);


alter table "public"."exits" enable row level security;

create table "public"."tags" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "name" character varying not null
);


alter table "public"."tags" enable row level security;

CREATE UNIQUE INDEX exit_tags_pkey ON public.exit_tags USING btree (id);

CREATE UNIQUE INDEX exits_pkey ON public.exits USING btree (id);

CREATE UNIQUE INDEX tags_name_key ON public.tags USING btree (name);

CREATE UNIQUE INDEX tags_pkey ON public.tags USING btree (id);

alter table "public"."exit_tags" add constraint "exit_tags_pkey" PRIMARY KEY using index "exit_tags_pkey";

alter table "public"."exits" add constraint "exits_pkey" PRIMARY KEY using index "exits_pkey";

alter table "public"."tags" add constraint "tags_pkey" PRIMARY KEY using index "tags_pkey";

alter table "public"."exit_tags" add constraint "exit_tags_exit_id_fkey" FOREIGN KEY (exit_id) REFERENCES exits(id) not valid;

alter table "public"."exit_tags" validate constraint "exit_tags_exit_id_fkey";

alter table "public"."exit_tags" add constraint "exit_tags_tag_id_fkey" FOREIGN KEY (tag_id) REFERENCES tags(id) not valid;

alter table "public"."exit_tags" validate constraint "exit_tags_tag_id_fkey";

alter table "public"."tags" add constraint "tags_name_key" UNIQUE using index "tags_name_key";
